theme: jekyll-theme-cayman
name: JManc
markdown: kramdown
title: JManc Unconference
baseurl: /
google_analytics: UA-116314007-1
social:
  name: Manchester Java Community
  links:
    - https://www.linkedin.com/groups/8270682/
